services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true 
    ControleOnline\:
        resource: '../../src/*'
        exclude: '../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}'
    ControleOnline\Repository\:
        resource: '../../src/Repository'
        tags: ['doctrine.repository_service']
    ControleOnline\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
    ControleOnline\Command\:
        resource: '../../src/Command'
        tags: ['console.command']
    ControleOnline\Filter\:
        resource: '../../src/Filter'
    ControleOnline\Service\N8NService:
        arguments:
            $n8nClient: '@http_client.n8n'
    http_client.n8n:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - { base_uri: '%env(N8N_WEBHOOK)%' }